[package]
name = "advent-of-code-2020"
version = "0.1.0"
authors = ["Walter Huf <hufman@gmail.com>"]

[dependencies]
aoc-runner = "0.3"
aoc-runner-derive = "0.3"
itertools = "0.9.0"
lazy_static = "1.4.0"
regex = "1"
uom = { version = "0.30.0", features = [ "u32", "u64", "i32", "i64" ] }
